### ISSUE TITLE
Compiling with CUDA&OpenCL: 'Lepton' not declared in this scope

### ISSUE THREAD

**Issue by jaimergp** [openmm/openmm-plumed#41]
I am trying to provide the conda recipes as suggested in #6. This is happening in this PR: https://github.com/conda-forge/staged-recipes/pull/13486

After the release of Plumed 2.7, the Reference platform can build correctly (see temporary CPU builds in the CI logs for [Linux](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=256052&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=2876) and [MacOS](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=256052&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7&t=fa7b4b17-b6ff-5c9c-8cfc-15f888c92310&l=3338)).

However, OpenCL and CUDA are not as lucky. There's an [issue with `lepton` and its scope in the OpenMM headers](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=256052&view=logs&j=780a49e0-e710-5ef4-04b1-64b406b2aebf&t=683df73a-89b2-5359-a175-5f009e5ed2e9&l=819):

```
Scanning dependencies of target OpenMMPlumedCUDA
[ 73%] Building CXX object platforms/cuda/CMakeFiles/OpenMMPlumedCUDA.dir/src/CudaPlumedKernelFactory.cpp.o
In file included from ${PREFIX}/include/openmm/cuda/CudaExpressionUtilities.h:30:0,
                 from ${PREFIX}/include/openmm/cuda/CudaContext.h:45,
                 from ${WORK}/platforms/cuda/src/CudaPlumedKernels.h:37,
                 from ${WORK}/platforms/cuda/src/CudaPlumedKernelFactory.cpp:35:
${PREFIX}/include/openmm/common/ExpressionUtilities.h:61:63: error: 'Lepton' was not declared in this scope
     std::string createExpressions(const std::map<std::string, Lepton::ParsedExpression>& expressions, const std::map<std::string, std::string>& variables,
                           
```

Any ideas? This is the [build script](https://github.com/jaimergp-feedstocks/staged-recipes/blob/openmm-plumed/recipes/openmm-plumed/build.sh).

**Comment by peastman** [comment]
Nothing obvious comes to mind.  That file includes several lepton headers, so it ought to be defined:

https://github.com/openmm/openmm/blob/e23dc9272ab4eafd72f91aace1320a7f1177ba7b/platforms/common/include/openmm/common/ExpressionUtilities.h#L32-L34

**Comment by jaimergp** [comment]
I have done some more digging. Turns out `plumed`'s conda package _also_ distributes `lepton` headers, which causes some kind of path confusion... Renaming that directory fixes it, I think.

**Comment by jaimergp** [comment]
Yep, that's it. Closing!
