### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by jaimergp** [openmm/openmm-plumed#42]
For the conda recipe I need the project to decide on a versioning scheme. Everything is almost ready in https://github.com/conda-forge/staged-recipes/pull/13486.

So far I resorted to YYYY.MM.DD, but I wonder if you'd rather choose a semver scheme with tagged releases in this repo?

**Comment by peastman** [comment]
Tagged releases sounds like a good idea.

**Comment by jaimergp** [comment]
May I ask for a tagged release then? 🙏

**Comment by peastman** [comment]
Is it ready to have the release made, or are there any final changes you want to check in first?

**Comment by jaimergp** [comment]
Hm, yep, good point. I need some local tests first, I guess.

Can you try [this](https://github.com/conda-forge/staged-recipes/pull/13486#issuecomment-752153440) on MacOS?

**Comment by jaimergp** [comment]
Ok, now we are ready for a release @peastman!

**Comment by peastman** [comment]
https://github.com/openmm/openmm-plumed/releases/tag/v1.0
