### ISSUE TITLE
Python unit test?

### ISSUE THREAD

**Issue by jaimergp** [openmm/openmm-plumed#46]
It'd be great to have at least one unit test for the Python wrappers so it can be included in the upcoming CI.

**Comment by raimis** [comment]
OK! I can just translate to Python one of these tests: https://github.com/openmm/openmm-plumed/blob/master/platforms/reference/tests/TestReferencePlumedForce.cpp

**Comment by jaimergp** [comment]
Yes, I think we would be ok with `testForce`. OpenMM-Torch [is doing something similar](https://github.com/openmm/openmm-torch/blob/master/python/tests/TestTorchForce.py).
