### ISSUE TITLE
Enabling plumed modules with conda install

### ISSUE THREAD

**Issue by mrjoness** [openmm/openmm-plumed#50]
Hello, 

Is it possible to enable a plumed module when installing via conda? For example:

`./configure --enable-modules=+piv+annfunc`

Or is the cmake route the only option here?

Thanks,
Mike

**Comment by invemichele** [comment]
The idea is to eventually create a `plumed-contrib` package on conda with all the contributed modules, but it's not here yet (see https://github.com/plumed/plumed2/issues/495)

**Comment by raimis** [comment]
> Or is the cmake route the only option here?

At the moment, it is only option. *OpenMM-PLUMED* just uses the *PLUMED* package.

**Comment by mrjoness** [comment]
thank you!
