### ISSUE TITLE
conda recipe for openmm-plumed 

### ISSUE THREAD

**Issue by msultan** [openmm/openmm-plumed#6]
So it seems like both [plumed](https://anaconda.org/acellera/plumed2) and openmm have conda recipes associated with them. Would it be possible to create a conda recipe for openmm-plumed to make it easier to install and deploy on travis?

**Comment by peastman** [comment]
Sounds like a good idea.

**Comment by jaimergp** [comment]
@peastman can you assign this to me?

**Comment by peastman** [comment]
Done.

**Comment by jaimergp** [comment]
PR opened here https://github.com/conda-forge/staged-recipes/pull/13486

**Comment by jaimergp** [comment]
The PR is now merged! 

* Packages: https://anaconda.org/conda-forge/openmm-plumed
* Feedstock: https://github.com/conda-forge/openmm-plumed-feedstock
* Install with `conda install -c conda-forge openmm-plumed`

**Comment by jaimergp** [comment]
@peastman This can be closed now.
