### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by k2o0r** [openmm/openmm-plumed#60]
Hello, I have now successfully built and installed both PLUMED and OpenMM into a conda environment but now run into some difficulties with the build of this plugin. The error message I get is quite long so I included just the start and end of it below.

<img width="1430" alt="Screenshot 2022-07-22 at 17 19 01" src="https://user-images.githubusercontent.com/67603864/180482023-0a2ebe5c-2337-4613-849c-b16355332d7b.png">
<img width="1238" alt="Screenshot 2022-07-22 at 17 19 35" src="https://user-images.githubusercontent.com/67603864/180482050-8afb6c2f-22e7-48a8-8ea4-3d57157d2998.png">

The ccmake settings used were as below:
<img width="883" alt="Screenshot 2022-07-22 at 17 23 17" src="https://user-images.githubusercontent.com/67603864/180482498-138e505b-7939-40b6-93d0-19a7887059a0.png">

Any help is much appreciated, thanks!

**Comment by raimis** [comment]
Is any reason why want to build from the source rather than installing with conda?

**Comment by k2o0r** [comment]
Yes, use of plumed modules not included in conda build.

**Comment by peastman** [comment]
Can you copy the full output of the build into a text file and attach it?  I suspect there may have been some additional information earlier in the build pointing to the root cause of the problem.

What version of OpenMM are you building against?

**Comment by k2o0r** [comment]
[build_output.txt](https://github.com/openmm/openmm-plumed/files/9169399/build_output.txt)
Like this?

I'm using openmm-7.7.0 from https://github.com/openmm/openmm/releases

**Comment by peastman** [comment]
Thanks!  That's a really confusing error.  It claims not to know about the `Lepton` namespace.  But right at the top of that file are several includes,

```c++
#include "lepton/CustomFunction.h"
#include "lepton/ExpressionTreeNode.h"
#include "lepton/ParsedExpression.h"
```

I expected the log would contain some earlier message about not being able to find those headers.  But it doesn't, which leaves me confused about what could be the cause of the error.

**Comment by k2o0r** [comment]
Could it be that the builds of OpenMM and PLUMED are not compatible somehow? 

I did build openmm (and this attempted build) on a compute node, and PLUMED on a login node. Does it seem possible this is the source of the error?

**Comment by peastman** [comment]
I thought about it, but I can't see how that would cause this error.  It's an error parsing the source code, not something in binary files.  The error also doesn't seem to be anything specific to the PLUMED plugin.  It's down in the OpenMM headers.

Is it possible your OpenMM install is somehow corrupt?  Could some of the header files be missing or truncated?

**Comment by k2o0r** [comment]
When I run  `make test` in OpenMM build directory everything passes (though it does seem quite slow for some reason), but not sure if this means that it's definitely not corrupt.

**Comment by peastman** [comment]
That's looking at compiled binaries.  The important thing here is the header files that get installed when you build.  Try looking at the specific files mentioned in the build output:

```
In file included from /home/kor20/miniconda3/envs/build_openmm/include/openmm/opencl/OpenCLExpressionUtilities.h:30,
                 from /home/kor20/miniconda3/envs/build_openmm/include/openmm/opencl/OpenCLContext.h:56,
                 from /home/kor20/openmm/openmm-plumed-1.0/platforms/opencl/src/OpenCLPlumedKernels.h:37,
                 from /home/kor20/openmm/openmm-plumed-1.0/platforms/opencl/src/OpenCLPlumedKernelFactory.cpp:35:
```

Compare those files to the ones that came from the source repository and make sure they're identical.  Also check for the Lepton headers included at the top of OpenCLExpressionUtilities.h.  Make sure they're present and not corrupt.

**Comment by k2o0r** [comment]
<img width="673" alt="Screenshot 2022-07-22 at 22 39 58" src="https://user-images.githubusercontent.com/67603864/180572326-0cd15ae7-de6c-4a89-b66f-709c336f9dee.png">

So here is OpenCLExpressionUtilities.h, I can't see any mention of Lepton but diff returns nothing between the file in the miniconda environment and from the source for both OpenCLExpressionUtilities.h and OpenCLContext.h.

**Comment by k2o0r** [comment]
`#include "ComputeContext.h"
#include "openmm/TabulatedFunction.h"
#include "lepton/CustomFunction.h"
#include "lepton/ExpressionTreeNode.h"
#include "lepton/ParsedExpression.h"
#include <map>
#include <sstream>
#include <string>
#include <utility>`

Aha, so I've now found the Lepton includes (in include/openmm/common/ExpressionsUtilities.h not include/openmm/opencl/ OpenCLExpressionUtilities.h).  The three lepton files included there look fine to me, but I'll post them here in case you want to check too because I am really quite out of my depth here. 

[CustomFunction.h.txt](https://github.com/openmm/openmm-plumed/files/9173468/CustomFunction.h.txt)
[ExpressionTreeNode.h.txt](https://github.com/openmm/openmm-plumed/files/9173469/ExpressionTreeNode.h.txt)
[ParsedExpression.h.txt](https://github.com/openmm/openmm-plumed/files/9173470/ParsedExpression.h.txt)

**Comment by k2o0r** [comment]
Sorry for post spam, but I've had some progress now.

Similar to posted here - https://github.com/openmm/openmm-plumed/issues/41, there was some path confusion between `include/lepton` and `include/plumed/lepton`. Renaming the latter to `include/plumed/lepton.bak` temporarily solved the issues above related to the Lepton headers and now the build reaches 100% but some errors do appear and the plugin doesn't appear to be working. I'll attach the new build output and the output from `python import openmmplumed` which both have errors.

[build_output_2.txt](https://github.com/openmm/openmm-plumed/files/9173549/build_output_2.txt)

[py_output.txt](https://github.com/openmm/openmm-plumed/files/9173554/py_output.txt)

S

**Comment by peastman** [comment]
The linker output indicates it can't find libcuda.so.  That library comes with the driver, not the toolkit, so make sure it's installed.  For example, if you're working on a cluster that has GPUs on the compute nodes but not the login nodes, it's possible the driver hasn't been installed on the login nodes.  If so, you won't be able to compile CUDA programs on them.

If that's not the problem, it may have to do with how you're compiling against a system tree installed inside your conda environment.  It only seems to be looking in directories that are inside `/home/kor20/miniconda3/envs/build_openmm/x86_64-conda-linux-gnu/sysroot`.  That isn't a location where the driver would have installed anything.  For example, on my computer it's installed in `/usr/lib/x86_64-linux-gnu`.  Can you find where it is on your computer?  Set the CMake variable `CUDA_cuda_driver_LIBRARY` (found under advanced options) to point to it.

**Comment by k2o0r** [comment]
Huh, this is a bit weird. So it seems you are right and that compilation can't find libcuda.so. When I open up the ccmake GUI this is what I see.

`CUDA_CUDART_LIBRARY              /home/kor20/miniconda3/envs/build_openmm/lib/libcudart.so`
                                                   
`CUDA_CUDA_LIBRARY                /usr/lib64/libcuda.so`

So, it's trying to access the libcuda.so in /usr/lib64 of the the cluster which is not the version of CUDA that this was compiled with. I wanted to find a version of libcuda.so in my conda environment, and there is /home/kor20/miniconda3/envs/build_openmm/lib/stubs/libcuda.so so I thought simply setting CUDA_CUDA_LIBRARY to this in ccmake GUI would work, but every time I configure after updating the path to libcuda.so (i.e. changing  to `CUDA_CUDA_LIBRARY            /home/kor20/miniconda3/envs/build_openmm/lib/stubs/libcuda.so`) it resets to `/usr/lib64/libcuda.so`, which then cannot be found during compilation.

**Comment by peastman** [comment]
I'm not sure exactly how it selects the value.  https://cmake.org/cmake/help/latest/module/FindCUDA.html describes the logic it goes through to locate libraries, but `CUDA_CUDA_LIBRARY` is not one of the variables they list as being set, so I'm not sure what's going on.  Still, that might help.

**Comment by ndonyapour** [comment]
Hi,
Removing `cuda` from this [line](https://github.com/openmm/openmm-plumed/blob/5406068b5a36b1208f1340180cfc5b8e4ee7aff9/platforms/cuda/tests/CMakeLists.txt#L14) fixed the issue for me.
