### ISSUE TITLE
How to correctly use openmm-plumed for system without periodic boundary condition

### ISSUE THREAD

**Issue by smliu1997** [openmm/openmm-plumed#61]
May I ask how to correctly set the plumed bias for periodic/non-periodic boundary systems (PBC or nonPBC)? In openmm, the periodic boundary condition is set for each single force, instead of set globally. There are methods to set forces as PBC or nonPBC. for example, for bond, there is ```setUsesPeriodicBoundaryConditions``` to set whether to use PBC for bonded interactions, and ```setNonbondedMethod``` for nonbonded interactions. So I wonder for plumed bias, if there is similar settings in openmm so that it can work properly for PBC and nonPBC systems? Another possibility is, whether to use PBC or not is only controlled by adding "NOPBC" or not in defining collective variables?

**Comment by peastman** [comment]
> Another possibility is, whether to use PBC or not is only controlled by adding "NOPBC" or not in defining collective variables?

Exactly.  It's determined by your PLUMED script.

**Comment by smliu1997** [comment]
Great, thanks!
