### ISSUE TITLE
Communication between multiple jobs (PBMetaD + multiple walkers + OpenMM or ENSAMBLE + OpenMM)

### ISSUE THREAD

**Issue by AlexanderJussupow** [openmm/openmm-plumed#69]
Hi,

I am currently trying to set up a PBMetaD simulation with multiple walkers with plumed and OpenMM. While I manage to start multiple PBMetaD simulations with MPI, I am struggling with figuring out how to make the simulations interact with each other so that all contribute to the common metadynamic potential. I also cannot get the ENSEMBLE function for replica averaging to work correctly for the same problem. I appreciate any suggestions. 

Best

Alex

**Comment by peastman** [comment]
The PLUMED plugin just implements a Force within a single simulation.  It doesn't support parallelization across multiple nodes.

You might look at the built in [Metadynamics class](http://docs.openmm.org/latest/api-python/generated/openmm.app.metadynamics.Metadynamics.html).  It does allow multiple walkers to contribute to the same potential.

**Comment by AlexanderJussupow** [comment]
Thank you for your response. I will try the Metadynamics class instead!

**Comment by AlexanderJussupow** [comment]
> The PLUMED plugin just implements a Force within a single simulation. It doesn't support parallelization across multiple nodes.
> 
> You might look at the built in [Metadynamics class](http://docs.openmm.org/latest/api-python/generated/openmm.app.metadynamics.Metadynamics.html). It does allow multiple walkers to contribute to the same potential.

Just to add it here in case somebody else is looking for a solution later on:
You can use the WALKERS_N, WALKERS_ID, WALKERS_RSTRIDE and WALKERS_DIR keyword to start the disk version of multiple walkers in METAD and PBMETAD. This is compatible with OpenMM. You need to additionally set RESTART to YES, otherwise not all replicas will read in all the hills files!

> WALKERS_N=4
> WALKERS_ID=0
> WALKERS_RSTRIDE=500
> WALKERS_DIR=../HILLS
> RESTART=YES
