### ISSUE TITLE
conda OSX-arm64?

### ISSUE THREAD

**Issue by gitkol** [openmm/openmm-plumed#75]
Hi, just wondering if there is a plan to provide conda installation on OSX-arm64?

Thanks,

   Istvan

**Comment by peastman** [comment]
I didn't realize there weren't any.  We certainly ought to have packages for it.  PLUMED is available, so there shouldn't be any problem with adding it.

**Comment by peastman** [comment]
We don't include a copy of PLUMED.  It comes from conda.  [Here is the feedstock](https://github.com/conda-forge/plumed-feedstock) where it gets built.  That's the place to ask about how it is compiled.

**Comment by gitkol** [comment]
I see. My bad, sorry.

**Comment by RaulPPelaez** [comment]
The build is being attempted here https://github.com/conda-forge/openmm-plumed-feedstock/pull/25
Any help is welcome, I am not well versed in OSX.

**Comment by gitkol** [comment]
I see that the OSX-64 version of openmm-plumed 2.0 is out but that won't run on Apple Silicon.
```
(openmm8) istvankolossvary@IstvansacStudio Downloads % conda install conda-forge::openmm-plumed
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - conda-forge::openmm-plumed

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

```
Is there a plan to do an arm64 build? I believe the included plumed package has been built on arm64.

Thanks!

   Istvan

**Comment by peastman** [comment]
We're working on it!  https://github.com/conda-forge/openmm-plumed-feedstock/pull/32.

**Comment by gitkol** [comment]
Thanks! Greatly appreciated.

**Comment by RaulPPelaez** [comment]
I do not have a Mac to check but the packages should be there now. @peastman if you can check please confirm and close this one.

**Comment by RaulPPelaez** [comment]
I have no idea and I do not have a Mac around to test it I am afraid...
The feedstock does check that importing openmmplumed works. I might had missed some nuisance specific to OSX, like search paths for dynamic libraries... 

Judging by the message your env seems to be missing the gsl library. But it is weird to me that the error did not appear in the feedstock to if that is the case.

**Comment by RaulPPelaez** [comment]
phew! thats a relieve. Lets close this one then. Thanks all!
