### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by RaulPPelaez** [openmm/openmm-plumed#76]
Now that OpenMM 8.1 is out we could release a new version that includes #70, it could be v1.1. I will go ahead if you are ok with it.

The release would include the following:

## What's Changed
* Add installation instructions for conda forge by @jaimergp in https://github.com/openmm/openmm-plumed/pull/44
* Add a unit test for the Python wrapper by @raimis in https://github.com/openmm/openmm-plumed/pull/47
* Add GH Actions based CI by @jaimergp in https://github.com/openmm/openmm-plumed/pull/45
* Fix type of argument to plumed_cmd by @GiovanniBussi in https://github.com/openmm/openmm-plumed/pull/71
* Fix failing CI builds by @peastman in https://github.com/openmm/openmm-plumed/pull/73
* Use CustomCPPForceImpl to simplify code by @peastman in https://github.com/openmm/openmm-plumed/pull/70

## New Contributors
* @jaimergp made their first contribution in https://github.com/openmm/openmm-plumed/pull/44
* @GiovanniBussi made their first contribution in https://github.com/openmm/openmm-plumed/pull/71

**Comment by raimis** [comment]
Looks good!

**Comment by RaulPPelaez** [comment]
New release is here: https://github.com/openmm/openmm-plumed/releases/tag/v1.1

**Comment by RaulPPelaez** [comment]
New conda-forge package is being built: https://github.com/conda-forge/openmm-plumed-feedstock/pull/28
The setup.py calls the current version 2.0 instead of 1.1.
Do we want to change setup.py to 1.1 or should I rename the release to v2.0?

**Comment by gitkol** [comment]
Hi, I noticed that openmm-plumed (via conda install -c conda-forge openmm-plumed) seemed no longer compatible with openmm 8.1 (also installed via conda-forge).
```
(openmm8.1-env) istvan@comp090:~/opt$ conda install -c conda-forge openmm-plumed
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                       

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - openmm-plumed -> python[version='3.10.*|3.11.*|3.9.*|3.8.*|3.7.*|3.6.*']
  - openmm-plumed -> python[version='>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0']

Your python: python=3.12

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.35=0
  - feature:|@/linux-64::__glibc==2.35=0
  - openmm-plumed -> __glibc[version='>=2.17']
  - openmm-plumed -> cudatoolkit[version='>=11.8,<12'] -> __glibc[version='>=2.17,<3.0.a0']

Your installed version is: 2.35
```
I tried to fall back on python and/or cudatoolkit to earlier versions and using python 3.9 I was actually able to install openmm-plumed, but then it didn't actually work, there were numerous libraries not found.

Since I see this new thread about a new version, I was wondering if there is a conda command to install v1.1 .

Thank you for your kind assistance.

Best regards,

   Istvan

**Comment by peastman** [comment]
Thanks for reminding us!  We still need to build the packages for the new version.

Raul, to answer your question above, it should be called 2.0.  This version uses a new feature in OpenMM 8.1 to radically simplify the code.  It's practically a rewrite.

**Comment by gitkol** [comment]
Oh, that sounds great! Could you then also build an arm64 version ? https://github.com/openmm/openmm-plumed/issues/75

**Comment by RaulPPelaez** [comment]
v2.0 has been built in conda-forge. Should be available for installation in a few hours.

**Comment by peastman** [comment]
Thanks!  I see the package are up now, so I'll close this.

**Comment by gitkol** [comment]
Thank you!
