### ISSUE TITLE
Looking for the wrong version of gsl

### ISSUE THREAD

**Issue by mixarcid** [openmm/openmm-plumed#84]
I just installed openmm-plumed via mamba (on Arch Linux). However, even running `python -c "import openmmplumed"` results in:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/boris/miniconda3/envs/dbfe/lib/python3.10/site-packages/openmmplumed.py", line 12, in <module>
    import _openmmplumed
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
```

I checked and there is a correctly installed libgsl.so.27 in the conda environemnt -- any ideas why it's looking for version 25?

I've attached my environment.yml file below in case that's helpful.
[environment.yml.txt](https://github.com/openmm/openmm-plumed/files/15382093/environment.yml.txt)

**Comment by peastman** [comment]
No idea.  That isn't something that this plugin or OpenMM uses directly.  Possibly it's a dependency of PLUMED?  Or maybe it's coming in through something completely different, like numpy?

**Comment by mixarcid** [comment]
Thanks for the quick reply!
I ended up solving this by downloading from gsl=2.7.1 to gsl=2.7.0. I have no idea why this helped.
