### ISSUE TITLE
Exposing C++ API to python

### ISSUE THREAD

**Issue by stefdoerr** [openmm/openmm-plumed#89]
Hi, I am trying to use the plugin through its python interface but it's missing a few crucial methods like:
```
setRestart
setMasses
setTemperature
setLogStream
```
Is there any reason why these were not exposed in the python interface and are only accessible via the C++ API?

**Comment by peastman** [comment]
I think it's just an oversight.  Those methods were added in #25, #26, #28, and #30.  They should have been added to the Python API but weren't.

**Comment by peastman** [comment]
I have all of them working except `get/setLogStream()`.  SWIG doesn't have any support for `FILE*`, and it's not clear how to represent them in Python.  Is it ok to omit those ones?

**Comment by peastman** [comment]
The implementation is in #90.  Can you try it out?

**Comment by stefdoerr** [comment]
Yes the logstream was not so important. I was thinking about passing a string with a file path to it instead if necessary but for now I don't mind too much.
Thanks for implementing them!

**Comment by stefdoerr** [comment]
Cool they all work. Thanks so much for implementing them!

**Comment by peastman** [comment]
Thanks!
